base/urls.py
from django.urls import path 
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteTask

urlpatterns = [
    path('', TaskList.as_view(), name='tasks'),
     path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
     path('create-task/', TaskCreate.as_view(), name='create-task'),
     path('update-task/<int:pk>/', TaskUpdate.as_view(), name='update-task'),
     path('delete-task/<int:pk>/', DeleteTask.as_view(), name='delete-task'),
     
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField (null=True, blank=True)
    complete = models.BooleanField (default=False)
    created = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(null=True, blank=True)
    

    PRIORITY_CHOICES = (
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'High'),
    )

    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']
       

base/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
   due_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'id': 'due_date'}))

class Meta:
        model = Task
        fields = ['title', 'description', 'complete', 'due_date', 'priority']
        widgets = {
            'complete': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

base/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from  django.contrib.auth.views import LoginView

from .models import Task

class TaskList(ListView):
    model = Task
    context_object_name= 'tasks'

class TaskDetail(DetailView):
    model = Task
    context_object_name= 'task'

class TaskCreate(CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('tasks')

class TaskUpdate(UpdateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('tasks')

class DeleteTask(DeleteView):
    model=Task
    context_object_name= 'task'
    success_url = reverse_lazy('tasks')


base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load bootstrap4 %}
    {% load widget_tweaks %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <title>Document</title>

    <style>
        body {
            margin: 20px;
            font-family: 'Roboto', sans-serif;

        }

        .bg-success {
            background-color: #d4edda !important;
        }

        .bg-warning {
            background-color: #fff3cd !important;
        }

        .bg-danger {
            background-color: #f8d7da !important;
        }

        .card-header {
            display: block;
            width: 100%;
            justify-content: space-between;
            color: whitesmoke;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            margin: auto;
            background: linear-gradient(90deg, rgba(113, 111, 147, 1) 0%, rgba(69, 109, 140, 0.8380602240896359) 59%, rgba(58, 127, 142, 1) 100%);
        }

        .link {
            text-decoration: none;
            color: beige;
        }

        .link:hover {
            color: blanchedalmond;
        }


        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }
    </style>

</head>

<body>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block extra_scripts %}
    <script src="https://unpkg.com/@popperjs/core@2.9.3/dist/umd/popper.js"></script>
    <script src="https://unpkg.com/bootstrap@5.0.1/dist/js/bootstrap.js"></script>
    {% endblock %}

</body>

</html>

base/templates/base/task_confirm_delete.html
{%extends 'base/main.html' %}
{% block content %}

<a href="{% url 'tasks' %}">Go back</a>
<p>You want to delete this task? "{{task}}"</p>
<form method="POST">
    {% csrf_token %}

    <input type="submit" value="Delete">
</form>

{% endblock content %}

base/templates/base/task_detail.html
<h1>Task {{task}}</h1>

base/templates/base/task_form.html
{%extends 'base/main.html' %}

{% load static %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'flatpickr/flatpickr.min.css' %}">
{% endblock %}

{% block content %}

{% load bootstrap4 %}
{% load widget_tweaks %}




<div class="card">

    <div class="card-header">
        <div>
            <h1>Hello!</h1>
        </div>
        <div>
            <h3>Add or edit your tasks</h3>
        </div>
        <a href="{% url 'tasks' %}" class="link mb-3">Go back</a>
    </div>
    <div class="card-body">
        <form method="POST" action="" class="mb-3">
            {% csrf_token %}

            {% bootstrap_form form %}

            <input type="submit" value="Submit" class="btn btn-primary">
        </form>

        <script src="{% static 'flatpickr/flatpickr.min.js' %}"></script>
        <script>
            flatpickr("#id_due_date", {
                dateFormat: "Y-m-d"
            });
        </script>
    </div>



</div>





{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %} {% block content %}

<div class="card">
    <div class="card-header">
        <div>
            <h1>Hello!</h1>
        </div>
        <div>
            <h3>Be more productive, finish your tasks</h3>
        </div>
    </div>
    <div class="card-body">
        <h5 class="card-title">Focus on your tasks</h5>
        <a href="{% url 'create-task' %}" class="btn btn-light">Add Task</a>
    </div>

    <ul class="list-group list-group-flush">
        {% for task in tasks %}
        <li
            class="list-group-item d-flex justify-content-between align-items-start {% if task.priority == 'L' %} bg-success {% endif %} {% if task.priority == 'M' %} bg-warning {% endif %} {% if task.priority == 'H' %} bg-danger {% endif %}">
            <div class="ms-2 me-auto">
                <div class="fw-bold">{{task.title}}</div>
                {{task.created}}
            </div>
            <div class="d-flex">
                <a href="{% url 'update-task' task.id %}" class="btn btn-primary btn-sm me-1">Edit</a>
                <button type="button" class="btn btn-danger btn-sm  " data-bs-toggle="modal"
                    data-bs-target="#exampleModal{{ task.id }}">
                    Delete
                </button>
            </div>
        </li>
        {% empty %}
        <h3>You don't have tasks</h3>
        {% endfor %}
    </ul>
</div>


{% for task in tasks %}
<!-- Modal -->
<div class="modal fade" id="exampleModal{{ task.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form method="POST" action="{% url 'delete-task' task.id %}">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{task.title}}"?</p>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}



{% endblock content %}